# Generated by Django 4.1.5 on 2023-01-09 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_proj', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event',
            new_name='category',
        ),
    ]
